title: Kai's First Blog
description: Welcome to my personal blog! Powered by GitHub Pages & Jekyll.

theme: jekyll-theme-cayman

# These are safe optional lines – they won't break anything
url: "https://ykaii3141.github.io"
baseurl: ""
